plugins:
  # Name could be anything, this name is what appears on the beginning of operation
  # mappings.
  plugin_name:
    # Could be 'central_deployment_agent' or 'host_agent'.
    # If 'central_deployment_agent', this plugin will be executed on the
    # deployment dedicated agent, other wise it will be executed on the host agent.
    executor: central_deployment_agent

    # URL to archive containing the plugin or name of directory containing
    # the plugin if it is included in the the blueprint directory under the
    # "plugins" directory.
    # Usage of "source" is supported, but not recommended, as it results in the
    # plugin going through `pip` installation on each and every agent (thus requiring
    # access to the `pip` repository/mirror, compilers and so forth).
    # Usage of plugin Wagon files, whenever possible, is recommended.
    # source: https://github.com/cloudify-cosmo/cloudify-plugin-template/archive/master.zip

    # The plugin's name, as it is known to Cloudify Manager. Cloudify Manager uses this
    # name to index the plugin in the plugins table.
    package_name: 'cloudify-equinix-metal-plugin'

    # The plugin's version. NOTE - it is recommended that this value is quoted, in order to
    # ensure it passes YAML parsing as a string (by default, the value "1.0" [without quotes]
    # will be parsed as a float).
    package_version: '1.0'

data_types:

  cloudify.types.common.SSHConfig:
    properties:
      host: 
        description: The IP address to connect to.
        type: string
        default: ''
        required: true
      username:
        description: The username to use for authentication.
        type: string
        default: 'root'
        required: false
      privatekey:
        description: The private key to use for authentication.
        type: string
        default: ''
        required: true
      commands:
        description: The commands to execute.
        type: list
        default: []
        required: true

  # you can build your data types for the properties that you will use inside the node_types
  cloudify.types.equinix.MetalConfig:
    properties:
      project_id:
        description: Your Equinix project id.
        type: string
        default: ''
        required: true
      api_key:
        description: Your Equinix api key.
        type: string
        default: ''
        required: true
      hostname:
        description: hostname.
        type: string
        default: ''
        required: true
      metro:
        description: Your Equinix location.
        type: string
        default: 'SV'
        required: true
      plan: 
        description: Your Equinix Metal plan.
        type: string
        default: 'c3.small.x86'
        required: true
      operating_system:
        description: Your Equinix Metal operating system.
        type: string
        default: 'ubuntu_22_04'
        required: true
      userdata:
        description: Your Equinix Metal userdata.
        type: string
        default: ''
        required: false

dsl_definitions:

  # you can define custom dsl defintions 
  # [ anchors that you can use to define common values or definitions between node definitions ]
  metal_config: &metal_config
    metal_config:
      type: cloudify.types.equinix.MetalConfig
      description: Your Equinix Project configuration.
      required: true

  ssh_config: &ssh_config
    ssh_config:
      type: cloudify.types.common.SSHConfig
      description: Your SSH Config
      required: true

node_types:

  # you can define your node_types here 
  cloudify.nodes.equinix.Metal:
    # you can use the derived_form 
    # [ to inherit the properties and interfaces of the node you are referencing ]
    derived_from: cloudify.nodes.Root
    # here you can add the properties that is relevant for you to interact with from the plugin python code
    properties:
      <<: *metal_config
    interfaces:
      # you can define the lifecycle operation 
      # and whatever operation that you may need this node_type to support
      cloudify.interfaces.lifecycle:
        create:
          implementation: plugin_name.plugin.equinix.plugin.create_metal_server
        delete:
          implementation: plugin_name.plugin.equinix.plugin.delete_metal_server
        stop:
          implementation: plugin_name.plugin.equinix.plugin.stop_metal_server
        restart:
          implementation: plugin_name.plugin.equinix.plugin.restart_metal_server
        uninstall:
          implementation: plugin_name.plugin.equinix.plugin.delete_metal_server
  
  # you can define your node_types here 
  cloudify.nodes.common.ScriptRunner:
    # you can use the derived_form 
    # [ to inherit the properties and interfaces of the node you are referencing ]
    derived_from: cloudify.nodes.Root
    # here you can add the properties that is relevant for you to interact with from the plugin python code
    properties:
      <<: *ssh_config
    interfaces:
      # you can define the lifecycle operation 
      # and whatever operation that you may need this node_type to support
      cloudify.interfaces.lifecycle:
        create:
          implementation: plugin_name.plugin.common.plugin.execute
     
